/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package marathon;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import static java.time.Instant.now;
import java.util.Date;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class MarathonApplication extends javax.swing.JFrame {

    /**
     * Creates new form MarathonApplication
     */
    
    static Timer timer;
    String dbname="marathonapp", dbpass="1234";
    
    public MarathonApplication() throws InterruptedException {
        initComponents();
        
        setVisible(true);
        setSize(700,500);
        setResizable(false);
        setLocationRelativeTo(null);
        setTitle("Marathon 2018");
        
        countdown();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        WelcomeScreen = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        panel01 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        HomeScreen = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel47 = new javax.swing.JLabel();
        StaffReg = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        ViewStaff = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList4 = new javax.swing.JList();
        Sponsor = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel30 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel46 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        Confirmation = new javax.swing.JPanel();
        RunnerReg = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        Register = new javax.swing.JPanel();
        jLabel48 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        WelcomeScreen.setBackground(new java.awt.Color(255, 255, 255));
        WelcomeScreen.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Marathon 2018");
        WelcomeScreen.add(jLabel1);
        jLabel1.setBounds(0, 160, 700, 70);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Come, let's run together!");
        WelcomeScreen.add(jLabel2);
        jLabel2.setBounds(190, 220, 330, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marathon/logo.jpg"))); // NOI18N
        WelcomeScreen.add(jLabel3);
        jLabel3.setBounds(280, 30, 160, 130);

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Enter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        WelcomeScreen.add(jButton1);
        jButton1.setBounds(280, 270, 140, 50);

        panel01.setBackground(new java.awt.Color(255, 255, 255));

        jLabel25.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        jLabel25.setText("The marathon starts in:");

        jLabel26.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel26.setText("00");

        jLabel27.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel27.setText(":");

        jLabel28.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel28.setText("00");

        jLabel32.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel32.setText(":");

        jLabel33.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel33.setText("00");

        jLabel34.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel34.setText(":");

        jLabel35.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel35.setText("00");

        javax.swing.GroupLayout panel01Layout = new javax.swing.GroupLayout(panel01);
        panel01.setLayout(panel01Layout);
        panel01Layout.setHorizontalGroup(
            panel01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel01Layout.createSequentialGroup()
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel28)
                .addGap(18, 18, 18)
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel35)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panel01Layout.setVerticalGroup(
            panel01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel01Layout.createSequentialGroup()
                .addGroup(panel01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panel01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel32)
                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel35)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        WelcomeScreen.add(panel01);
        panel01.setBounds(40, 350, 620, 70);

        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        WelcomeScreen.add(jLabel4);
        jLabel4.setBounds(30, 10, 640, 440);

        getContentPane().add(WelcomeScreen, "card2");

        HomeScreen.setBackground(new java.awt.Color(204, 204, 255));
        HomeScreen.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Marathon 2018");
        HomeScreen.add(jLabel5);
        jLabel5.setBounds(158, 11, 360, 60);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("<html>The marathon is a long-distance race, completed by running, walking , or a run/walk strategy. There are also wheelchair divisions. The marathon has an official distance of 42.195 kilometres (26.219 miles, or 26 miles 385 yards), usually run as a road race. The event was instituted in commemoration of the fabled run of the Greek soldier Pheidippides, a messenger from the Battle of Marathon to Athens, who reported the victory.  The marathon was one of the original modern Olympic events in 1896, though the distance did not become standardized until 1921. More than 800 marathons are held throughout the world each year, with the vast majority of competitors being recreational athletes as larger marathons can have tens of thousands of participants.</html>");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        HomeScreen.add(jLabel6);
        jLabel6.setBounds(40, 70, 630, 200);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setText("Registeration");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        HomeScreen.add(jButton2);
        jButton2.setBounds(400, 350, 200, 70);

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton3.setText("View Staff List");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        HomeScreen.add(jButton3);
        jButton3.setBounds(110, 350, 210, 70);

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton7.setText("More");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        HomeScreen.add(jButton7);
        jButton7.setBounds(590, 20, 61, 23);

        jLabel47.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel47.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel47.setText("Configure Database");
        jLabel47.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel47MouseClicked(evt);
            }
        });
        HomeScreen.add(jLabel47);
        jLabel47.setBounds(560, 440, 120, 20);

        getContentPane().add(HomeScreen, "card3");

        StaffReg.setBackground(new java.awt.Color(255, 204, 204));
        StaffReg.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Staff Members register here:");
        StaffReg.add(jLabel7);
        jLabel7.setBounds(90, 30, 520, 60);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("First Name");
        StaffReg.add(jLabel8);
        jLabel8.setBounds(180, 110, 90, 30);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("Last Name");
        StaffReg.add(jLabel9);
        jLabel9.setBounds(180, 150, 100, 40);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("Email id");
        StaffReg.add(jLabel10);
        jLabel10.setBounds(177, 194, 112, 29);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setText("Phone");
        StaffReg.add(jLabel11);
        jLabel11.setBounds(177, 241, 112, 28);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setText("Designation");
        StaffReg.add(jLabel12);
        jLabel12.setBounds(177, 287, 112, 27);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setText("Shift");
        StaffReg.add(jLabel13);
        jLabel13.setBounds(177, 332, 112, 26);
        StaffReg.add(jTextField1);
        jTextField1.setBounds(340, 110, 200, 26);
        StaffReg.add(jTextField2);
        jTextField2.setBounds(340, 150, 200, 24);
        StaffReg.add(jTextField3);
        jTextField3.setBounds(340, 190, 200, 29);
        StaffReg.add(jTextField4);
        jTextField4.setBounds(340, 240, 200, 28);
        StaffReg.add(jTextField5);
        jTextField5.setBounds(340, 290, 200, 27);
        StaffReg.add(jTextField6);
        jTextField6.setBounds(340, 330, 200, 26);

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton4.setText("Submit");
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        StaffReg.add(jButton4);
        jButton4.setBounds(299, 412, 115, 39);
        StaffReg.add(jLabel14);
        jLabel14.setBounds(550, 330, 140, 30);
        StaffReg.add(jLabel15);
        jLabel15.setBounds(550, 110, 140, 30);
        StaffReg.add(jLabel16);
        jLabel16.setBounds(550, 150, 140, 30);
        StaffReg.add(jLabel17);
        jLabel17.setBounds(550, 190, 140, 30);
        StaffReg.add(jLabel18);
        jLabel18.setBounds(550, 240, 140, 30);
        StaffReg.add(jLabel19);
        jLabel19.setBounds(550, 290, 140, 30);

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton6.setText("Back");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        StaffReg.add(jButton6);
        jButton6.setBounds(20, 20, 100, 30);

        getContentPane().add(StaffReg, "card4");

        ViewStaff.setBackground(new java.awt.Color(204, 255, 204));
        ViewStaff.setLayout(null);

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Staff List");
        ViewStaff.add(jLabel20);
        jLabel20.setBounds(170, 20, 380, 50);

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel21.setText("Sr. No");
        ViewStaff.add(jLabel21);
        jLabel21.setBounds(40, 100, 70, 30);

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel22.setText("Name");
        ViewStaff.add(jLabel22);
        jLabel22.setBounds(160, 100, 150, 30);

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel23.setText("Designation");
        ViewStaff.add(jLabel23);
        jLabel23.setBounds(330, 100, 78, 18);

        jLabel24.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel24.setText("Shift");
        ViewStaff.add(jLabel24);
        jLabel24.setBounds(510, 100, 124, 30);

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        ViewStaff.add(jButton5);
        jButton5.setBounds(30, 20, 110, 30);

        jList1.setBackground(new java.awt.Color(204, 255, 204));
        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        ViewStaff.add(jScrollPane1);
        jScrollPane1.setBounds(140, 140, 150, 300);

        jList2.setBackground(new java.awt.Color(204, 255, 204));
        jList2.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList2);

        ViewStaff.add(jScrollPane2);
        jScrollPane2.setBounds(30, 140, 80, 300);

        jList3.setBackground(new java.awt.Color(204, 255, 204));
        jList3.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList3);

        ViewStaff.add(jScrollPane3);
        jScrollPane3.setBounds(320, 140, 160, 300);

        jList4.setBackground(new java.awt.Color(204, 255, 204));
        jList4.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(jList4);

        ViewStaff.add(jScrollPane4);
        jScrollPane4.setBounds(500, 140, 140, 300);

        getContentPane().add(ViewStaff, "card5");

        Sponsor.setBackground(new java.awt.Color(204, 255, 204));

        jLabel29.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Sponsor a runner");

        jComboBox2.setMaximumRowCount(20);

        jLabel30.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel30.setText("Credit Card Information:");

        jButton8.setText("Back");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel31.setText("Credit card number");

        jLabel44.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel44.setText("CVV");

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        jLabel45.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel45.setText("Expiry Date");

        jTextField10.setText("10");

        jButton9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton9.setText("+");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton10.setText("-");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabel46.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel46.setText("Sponsership Amount");

        jButton11.setBackground(new java.awt.Color(255, 255, 255));
        jButton11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton11.setText("Submit");
        jButton11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SponsorLayout = new javax.swing.GroupLayout(Sponsor);
        Sponsor.setLayout(SponsorLayout);
        SponsorLayout.setHorizontalGroup(
            SponsorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SponsorLayout.createSequentialGroup()
                .addGroup(SponsorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SponsorLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jButton8)
                        .addGap(76, 76, 76)
                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SponsorLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SponsorLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SponsorLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SponsorLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SponsorLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(SponsorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(SponsorLayout.createSequentialGroup()
                                .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(14, 14, 14)
                        .addComponent(jButton9)
                        .addGap(10, 10, 10)
                        .addComponent(jButton10))
                    .addGroup(SponsorLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        SponsorLayout.setVerticalGroup(
            SponsorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SponsorLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(SponsorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton8)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(SponsorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(SponsorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(SponsorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SponsorLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(SponsorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SponsorLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(SponsorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        getContentPane().add(Sponsor, "card6");

        javax.swing.GroupLayout ConfirmationLayout = new javax.swing.GroupLayout(Confirmation);
        Confirmation.setLayout(ConfirmationLayout);
        ConfirmationLayout.setHorizontalGroup(
            ConfirmationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 703, Short.MAX_VALUE)
        );
        ConfirmationLayout.setVerticalGroup(
            ConfirmationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        getContentPane().add(Confirmation, "card7");

        RunnerReg.setBackground(new java.awt.Color(102, 255, 204));
        RunnerReg.setLayout(null);

        jLabel49.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel49.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel49.setText("Runner Registeration");
        RunnerReg.add(jLabel49);
        jLabel49.setBounds(140, 50, 410, 50);

        jLabel50.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel50.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel50.setText("Name:");
        RunnerReg.add(jLabel50);
        jLabel50.setBounds(160, 150, 130, 30);

        jLabel51.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel51.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel51.setText("Country code:");
        RunnerReg.add(jLabel51);
        jLabel51.setBounds(160, 210, 130, 30);
        RunnerReg.add(jTextField11);
        jTextField11.setBounds(310, 150, 180, 30);
        RunnerReg.add(jTextField12);
        jTextField12.setBounds(310, 210, 180, 30);

        jCheckBox1.setBackground(new java.awt.Color(102, 255, 204));
        jCheckBox1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jCheckBox1.setText(" You agree to the terms and conditions for Marathon 2018");
        RunnerReg.add(jCheckBox1);
        jCheckBox1.setBounds(200, 270, 310, 20);

        jCheckBox2.setBackground(new java.awt.Color(102, 255, 204));
        jCheckBox2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jCheckBox2.setText(" You agree to abide by Marathon's code of conduct");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        RunnerReg.add(jCheckBox2);
        jCheckBox2.setBounds(210, 300, 280, 20);

        jButton15.setBackground(new java.awt.Color(255, 255, 255));
        jButton15.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton15.setText("Back");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        RunnerReg.add(jButton15);
        jButton15.setBounds(20, 20, 61, 25);

        jButton16.setBackground(new java.awt.Color(255, 255, 255));
        jButton16.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton16.setText("Submit");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        RunnerReg.add(jButton16);
        jButton16.setBounds(280, 350, 120, 30);

        getContentPane().add(RunnerReg, "card8");

        Register.setBackground(new java.awt.Color(255, 255, 153));
        Register.setLayout(null);

        jLabel48.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel48.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel48.setText("Registeration");
        Register.add(jLabel48);
        jLabel48.setBounds(190, 70, 290, 60);

        jButton12.setBackground(new java.awt.Color(255, 255, 255));
        jButton12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton12.setText("Back");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        Register.add(jButton12);
        jButton12.setBounds(20, 20, 100, 30);

        jButton13.setBackground(new java.awt.Color(255, 255, 255));
        jButton13.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton13.setText("Runner Registeration");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        Register.add(jButton13);
        jButton13.setBounds(220, 210, 230, 50);

        jButton14.setBackground(new java.awt.Color(255, 255, 255));
        jButton14.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton14.setText("Staff Registeration");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        Register.add(jButton14);
        jButton14.setBounds(220, 310, 230, 50);

        getContentPane().add(Register, "card9");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        WelcomeScreen.setVisible(false);
        HomeScreen.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    boolean error = false;
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String fname = jTextField1.getText();
        String lname = jTextField2.getText();
        String email = jTextField3.getText();
        String phone = jTextField4.getText();
        String desig = jTextField5.getText();
        String shift = jTextField6.getText();
        
        if(fname.equals("")||lname.equals("")||email.equals("")||phone.equals("")||desig.equals("")||shift.equals("")) {
            
            JOptionPane.showMessageDialog(this, "Fill out all the fields");
            error = true;
        }
        else {
            if(!email.contains("@")||!email.contains(".com")) {
                jLabel17.setText("Enter a valid email id!");
                error = true;
            }
            else{
                error = false;
            }
            
            if(phone.length()>10||phone.length()<10) {
                jLabel18.setText("Enter a valid phone number");
                error = true;
            }
            else {
                error = false;
            }
        }
            
            
            if(error==false) {
                
            try
                {
    Class.forName("com.mysql.jdbc.Driver");
    Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/"+dbname,"root",dbpass);
    Statement stmt=con.createStatement();
   
    stmt.execute("create table if not exists staff(first_name varchar(48), last_name varchar(48), email varchar(128), phone varchar(48), designation varchar(48), shift varchar(32), primary key(first_name, last_name))");
    stmt.executeUpdate("insert into staff(first_name,last_name,email,phone,designation, shift)values('"+fname+"','"+lname+"','"+email+"','"+phone+"','"+desig+"','"+shift+"')");
   
    JOptionPane.showMessageDialog(null,"Account created");
    
    jTextField4.setText(null);
    jTextField5.setText(null);
    jTextField6.setText(null);
    jTextField1.setText(null);
    jTextField2.setText(null);
    jTextField3.setText(null);
    jLabel17.setText(null);
    jLabel18.setText(null);
    
   
    }
    catch(Exception e) {   
            System.out.println(e);
        }
      }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        HomeScreen.setVisible(false);
        Register.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        
        HomeScreen.setVisible(false);
        ViewStaff.setVisible(true);
        viewData();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        ViewStaff.setVisible(false);
        HomeScreen.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        StaffReg.setVisible(false);
        Register.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        Sponsor.setVisible(false);
        HomeScreen.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        Sponsor.setVisible(true);
        HomeScreen.setVisible(false);     
        getRunners();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
       
//submit clicked
try {
        boolean error=false;
        
        String runner = jComboBox2.getSelectedItem().toString();
        String creditcard = jTextField7.getText();
        String cvv = jTextField8.getText();
        String expdate = jTextField9.getText();
        String amount = jTextField10.getText();
        
        
        if(creditcard.equals("")||cvv.equals("")||expdate.equals("")||amount.equals("")) {
            error=true;
            JOptionPane.showMessageDialog(this, "Enter valid information!");
        }
        else {
        SimpleDateFormat sdf = new SimpleDateFormat("MM/yyyy");
        Date d = (Date) sdf.parse(expdate);
        Date d1 = new Date();
             if(creditcard.length()>16||creditcard.length()<16) {
                error=true;
            }
            
            if(cvv.length()>3||cvv.length()<3) {
                error=true;
            }
            
            if(!d.after(d1)) {
                error=true;
            }
            System.out.println(error);}
            
        
        if(error==false) {                
                try {
                    
                    Class.forName("com.mysql.jdbc.Driver");
                    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/"+dbname,"root",dbpass);
                    Statement stmt = con.createStatement();
                    
stmt.executeUpdate("update runner_record set sponsorship="+amount+" where name='"+runner+"'");

Sponsor.setVisible(false);
Confirmation.setVisible(true);
                    
                }
                catch (Exception e) {
                    System.out.println(e);
                }
                
            
        }
        
}
catch (Exception e) {
    System.out.println(e);
}
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        int a = Integer.parseInt(jTextField10.getText())+10;
        jTextField10.setText(""+a);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        int a = Integer.parseInt(jTextField10.getText())-10;
        jTextField10.setText(""+a);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jLabel47MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel47MouseClicked
        // configure database
        dbname = JOptionPane.showInputDialog("Enter database name (MySQL): \n(Do not create a new database. Use an existing one.)");
        dbpass = JOptionPane.showInputDialog("Enter MySQL password (if exists): ");
    }//GEN-LAST:event_jLabel47MouseClicked

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // Back - from registeration to homescreen
        Register.setVisible(false);
        HomeScreen.setVisible(true);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // Staff registeration button
        Register.setVisible(false);
        StaffReg.setVisible(true);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // runner registeration button
        Register.setVisible(false);
        RunnerReg.setVisible(true);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        RunnerReg.setVisible(false);
        Register.setVisible(true);
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        //submit - runner registeration
        String name = jTextField11.getText();
        int ccode = Integer.parseInt(jTextField12.getText());
        if(jCheckBox1.isSelected() && jCheckBox2.isSelected()) {
            if(ccode  > 999) {
                JOptionPane.showMessageDialog(this, "Enter a valid country code");
            }
            else {
                try {
                    Class.forName("com.mysql.jdbc.Driver");
                    if(dbname.equals(null)) {
                        dbname="marathonapp";
                    }
                    if(dbpass.equals(null)) {
                        dbpass="1234";
                    }
                    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/"+dbname,"root",dbpass);
                    Statement stmt = con.createStatement();
                    
                    stmt.executeUpdate("insert into runner_record(name, countrycode) values ('"+name+"','"+ccode+"')");
                    JOptionPane.showMessageDialog(this, "Registered Successfully!");
                }
                catch(Exception e) {
                    System.out.println(e);
                }                
            }
        }
        else {
            JOptionPane.showMessageDialog(this, "You must check both the checkboxes!");
        }
    }//GEN-LAST:event_jButton16ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MarathonApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MarathonApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MarathonApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MarathonApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MarathonApplication().setVisible(true);
                } catch (InterruptedException ex) {
                    Logger.getLogger(MarathonApplication.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Confirmation;
    private javax.swing.JPanel HomeScreen;
    private javax.swing.JPanel Register;
    private javax.swing.JPanel RunnerReg;
    private javax.swing.JPanel Sponsor;
    private javax.swing.JPanel StaffReg;
    private javax.swing.JPanel ViewStaff;
    private javax.swing.JPanel WelcomeScreen;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JList jList3;
    private javax.swing.JList jList4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JPanel panel01;
    // End of variables declaration//GEN-END:variables

    void viewData() {
        try {
            
        Class.forName("com.mysql.jdbc.Driver");
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/"+dbname,"root",dbpass);
        
        String query = "select * from staff";
        
        PreparedStatement pst =  con.prepareStatement(query);   
        
        ResultSet rs = pst.executeQuery();
        int i = 1;
        
        DefaultListModel<String> dlm = new DefaultListModel<>();
        DefaultListModel<String> sr = new DefaultListModel<>();
        DefaultListModel<String> des = new DefaultListModel<>();
        DefaultListModel<String> time = new DefaultListModel<>();
        
        while(rs.next()) {
            sr.addElement(""+i);
            i++;
            dlm.addElement(rs.getString("first_name")+" "+rs.getString("last_name"));
            des.addElement(rs.getString("designation"));
            time.addElement(rs.getString("shift"));
        }
        
        jList1.setModel(dlm);
        jList2.setModel(sr);
        jList3.setModel(des);
        jList4.setModel(time);
        
        }
        catch (Exception e) {
            System.out.println(e);
        }
    }
    
    void getRunners() {
        try {
        Class.forName("com.mysql.jdbc.Driver");
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/"+dbname,"root",dbpass);
        String query="Select * from runner_record";
        PreparedStatement pst=con.prepareStatement(query);
        ResultSet rs = pst.executeQuery();
        
        while(rs.next()) {
            jComboBox2.addItem(new comboBox2(rs.getString("name")));
            jComboBox1.addItem(new comboBox1(rs.getString("countrycode")));
            
        }
        
        }
        catch (Exception e) {
            System.out.println(e);
        }
    }
    
    int interval;
    
    void countdown() throws InterruptedException {
        try {
                    SimpleDateFormat sdf=new SimpleDateFormat("dd-MM-yyyy");
                        timer = new Timer();
                        int period = 1000;
                        int delay = 1000;
                        interval = 9288181;
                        timer.scheduleAtFixedRate(new TimerTask() {

                            @Override
                            public void run() {
                                
                                setInterval();
        
        int days = interval/(24*60*60);
        int hours = interval%(24*60*60)/(60*60);
        int minutes = (interval/ 60) % 60;
        int seconds = (interval)%60 ;
                                    
                                    
                        jLabel26.setText(""+days);
                        jLabel28.setText(""+hours);
                        jLabel33.setText(""+minutes);
                        jLabel35.setText(""+seconds);
                            }
                        }, delay, period);
        
        }
        catch(Exception e) {
            System.out.println(e);
        }
    }
    
    int setInterval() {
        if (interval == 1) 
            
            timer.cancel();
            
            return --interval;
        
    }
    
    class comboBox2 {
        
        String value;
        
        public comboBox2(String value) {
            this.value = value;
        }
        
        @Override
        public String toString(){
            return value;
        }
        
    }
    
    class comboBox1 {
        String value;
        
        public comboBox1(String value) {
            this.value = value;
        }
        
        @Override
        public String toString() {
            return value;
        }
    }
    
}
